### ISSUE TITLE
hexbound entries don't appear in in-game book

### ISSUE THREAD

**Issue by kristifristi** [Cypher121/hexbound#3] opened 2023-02-17 10:55 UTC
![noentries](https://user-images.githubusercontent.com/65536944/219627772-30080fc3-51bd-4aed-ab02-fe13460e5003.jpg)

**Comment by Cypher121** [comment] 2023-02-17 15:40
Huh, categories are there but not entries? Frankly no idea how that'd happen.

**Comment by Cypher121** [comment] 2023-02-17 15:41
Could you try removing and then giving yourself back the `hexcasting:root` advancement?

**Comment by kristifristi** [comment] 2023-02-17 16:41
they still don't show up
also just in case for clarity, it's every entry, not just the construct ones

**Comment by Cypher121** [comment] 2023-02-18 04:59
Are there any hexbound or patchouli related errors in the logs?

**Comment by MrFire24** [comment] 2023-02-19 22:13
[00:11:44] [Render thread/ERROR]: Error loading extending book hexcasting:thehexbook with addon book hexbound:hexboundbook, skipping
java.lang.RuntimeException: Entry in file hexbound:patchouli_books/hexboundbook/en_us/entries/interop/hexal_interop.json does not have a valid category.
	at vazkii.patchouli.client.book.BookEntry.initCategory(BookEntry.java:146)
	at vazkii.patchouli.client.book.BookContentsBuilder.loadEntry(BookContentsBuilder.java:164)
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$loadFrom$0(BookContentsBuilder.java:80)
	at vazkii.patchouli.client.book.BookContentsBuilder.load(BookContentsBuilder.java:127)
	at vazkii.patchouli.client.book.BookContentsBuilder.loadFrom(BookContentsBuilder.java:79)
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:216)
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:128)
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63)
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34)
	at net.minecraft.class_632.handler$zgn000$patchouli_onSync(class_632.java:1017)
	at net.minecraft.class_632.method_2861(class_632.java:57)
	at net.minecraft.class_634.method_11130(class_634.java:1269)
	at net.minecraft.class_2779.method_11925(class_2779.java:51)
	at net.minecraft.class_2779.method_11054(class_2779.java:16)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1129)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

**Comment by Cypher121** [comment] 2023-02-20 02:48
Okay, this one turned out REALLY weird and is caused by the interop category not being present. While I work on a fix, the workaround is to install Gravity API or Pehkui so the category turns on.

**Comment by Cypher121** [comment] 2023-03-03 18:27
Fixed in 0.1.1

**Closed by Cypher121** 2023-03-03 18:27 UTC
